### ISSUE TITLE
Expand Synology install instructions

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/website#10]
@andypiper wrote some here, we should adapt that into the official docs: https://andypiper.co.uk/2023/07/05/running-a-3d-print-catalogue-with-van-dam/

**Comment by andypiper** [comment]
... 😬 I should probably check that's still valid!

**Comment by Floppy** [comment]
Heh - well, it's linked from the main website now! https://manyfold.app/get-started/synology-nas.html

(I'll replace it at some point with an official set of instructions)

**Comment by andypiper** [comment]
I'll try to update my installation from VanDAM to Manyfold this weekend.
